tra_dataset_path: "/yout_path/widerface/train"
val_dataset_path: "/yout_path/widerface/val"
batch_size: 8
dummy_input: [[1,3,480,480]]
channel: 3
height: 480
width: 480
fp32_min: -1.0
fp32_max: 1.0
image_size: [480,480]
min_sizes: [[16, 32], [64, 128], [256, 512]]
steps: [8,16,32]
match_thresh: 0.45
ignore_thresh: 0.3
variances: [0.1, 0.2]
clip: False
