train_clean_wave_path: "/your_path/rnnwave/clean_trainset_56spk_wav/"
train_noisy_wave_path: "/your_path/rnnwave/noisy_trainset_56spk_wav/"
clean_wave_path: "/your_path/rnnwave/clean_testset_wav"
noisy_wave_path: "/your_path/rnnwave/noisy_testset_wav"
dummy_input: [[1,1,42],[1,24],[1,48],[1,96]]
recursive_input: [[1,3],[2,2],[3,0]]
batch_size: 1
channel: 1
height: 42
width: 1
fp32_min: -41.1027
fp32_max: 41.2633
